# name of the workflow
name: First Workflow
# When this workflow should execute. workflow_dispatch means it should run manually
on: workflow_dispatch
jobs: 
  #name of the job. Any name we can specify
  first-job:
    # define the environment you want to use
    runs-on: ubuntu-latest
    steps:
      # Name of the step
      - name: print Greetings
        # Run the command
        run: echo "Hello World"
      - name: print Bye
        # Run the command. to run multiple shell commands by adding the pipe symbol (|)
        run: |
          echo "Thank you"
          echo "Done Bye"
        

